# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

#name: registernode
name: allen-bradley
version: "1.0.01"
grade: stable
summary: App to pull data from and Allen-Bradley Controller  #Sample app to register 'myData' node on ctrlX Data Layer
description: |
  This app will read the AB.json file at the root of the activeConfiguration to subsribe and produce data. 
base: core18
confinement: strict

# define how apps & services are exposed to host system
apps:
  registerNode:
    command: allen-bradley
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: [network, network-status, network-bind, process-control]
    daemon: simple

parts:
  allen-bradley:
    plugin: dump
    source: ./generated/build

  #flatbuffers:
  #  plugin: dump
  #  source: ./bfbs

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 

  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions    
